travis:
  secure:
    BINSTAR_TOKEN: iDElZZKWLeObvMr7OxzCDg3cX/bb76Xr4rcp+y2jnoHSq7WN14r1fa9CxzFI/c2wGkxt1U+ML0k+FsKYSCzTf1Kgd38D+za3LbPQgh/z1guAxJBZJjK4B1+JzTBKzyNNYbTSQFIsZ99hbWuy6VIRTnDMAViCCke+SrovOGyl2wQNWTEreK+uiTyQEVHYqIhsHd3eNZlnyKgYC24VVMSWM0gXvnMiwUrVmyetOzdNAKCOf8ZPkVGs8o+lRiHoyk41lTV7vqA+KXdzVNuYLZL0AkJPYRCOkItiQ+apm6C2zHqvQ4GnKPUAE4OQdRn9T8ghFQml+noIfOgm+o1VPfXwb05w02hjnVi7OUKJY93VpvMecjXLAM3f1ntB1RYRDZs8Lnfp3Ixu7Rz5A8H3SQ1+X7Nea+d+noX0f76NVxYITOdfiIEnC5J3NALRa0SHh4mfCbNUbjQ4nYv4S4r6CMKsufxEDNJC1HmROzZQb9PVgZiAlzzWHqjCVgUjQ4A+/fLs/8dqNTv5W1r8bwZ388Loqt25aerJaGCqUS6mlPwWEg0xZKXdvCmfPloLyAqyiyRrE6VySk+gQySIsFHze6VQ1ZhQZt9U1pRw1puPyNBgNT90YK1afP6dk8/t5KVhGLWpVzhVsiQKm5StI3MajCwuTuCeJXSWuoNdI95eZZRJx60=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
