travis:
  secure:
    BINSTAR_TOKEN: jDiCorBR7h2zvkoV21IwpnpFP5kYbp/eDnGQyQo5FPMYA7JW75YzXER8L975Q9hr9+ahrDwUMOwK2ZjWmz07ZkmZT3OfePXjoigZyuvkKu/ZyH9/0sM26qUCLMUn7idUtwy6Z82aFmo5Qc/qJy10Gn9UyLQvi1yDniy1KZdW0U58qr/oP8pCGSGSArvpbzD7sQpx6M2C78rHOnBE7UGFJOczMOJmCaunKeBHlUkNmKroyEVSbIBu6F/F3xTis+Z4JRqXYLgZiVaZ/vy4vQYPI9Wkrn9qot3e/C1Xx+SH+oDozTx94qptJQtcwaWIbSY52E+76ZdEkfiEcfpMel+GaTcHBXmfNC3NFlGeOra//Qzgl4kbbjQqrmu7+Ma+3vGJtzafcnqm0xfzHAR9DmJK8/AVC87wisU8hqpIWUnxnFJFPVZt6x6ch4O96W02ewW3KjIW2JaSfbNTSemh3VuXox3S2eUA8oTNhI0aIjm/NDwCQry7DFxLnnToTD6w3EK9pGMTDMP/tcC7MLIPXbeHVbi1MYeT7913LIq4cLzTkKu//GAKwT6P3W0xkz32kYh+1YbVZq7DOdGlofjojfHiDOfpS9bn8EZZRAPHkGqA+8ilpb/yjFLHLxB1CuZ+TR+MN6t5EdCQG018L9WcJpV7oA/5FBVLPCcf7ja77/ZBLaM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
