travis:
  secure:
    BINSTAR_TOKEN: ecfDCU4/ZdxPxBuJ23+bPoKm4SlGzZdy7C3W+kXPq+VqCaQh781qFdTHNmM/nGWs1mm1vT4pyWZzZWu0WScDqBdVuHKTMzpQhNC/WEFobllW8MXeKWMVu7JQjVw8DTfSwT/0rUQjUadB8RXUCWnrBua3klzD7heKnLp69vCEWQ2uh2BM72hGbtN0sj6Q5g52yf4BDZqWIxysTMNVMvIbV7AmuacegUC//APYOoGpypkoeH8CNHRMZTcPdX8GqLwlKhQ8X5RqFLKiTxUy97B+cYOxZQ3Do+vAAXbs1p8/tz5O5vfiXJepvOQzbe2pDhxD/x67Fp2GZTljt2HEbmkCx/uqSGhdYyHCFL27QTzkvWeCgmaOOEJp6q6qL6gP7OJPXO2f5dxvGwqM8hkEjolC7zkufx0sw5RCmt0hxDPL9p/mrMrQzLBI823wnBbqdRI0wYvTs3WSH1pMtkRKBFMhkrmnZVd97EObyOAplWw6Kqxc3G4812Hv689cQTX8tFA5Cs8mSYgrXu0nRWvVYkuRsEX/Ftm3bSkjLTs5pSOXTJyfVS5jMtK0T0EOMLNqJcI4nVBLTB9AgIbjXCnUK7gHQ1BbQ9pWQv87L+RMpbQVrX+6B1N4tj2xkvtxD4drFhavnVqU5FLaNw8UBBt+/tKHwhueUL+W+EBAjROOIlzym8M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
