travis:
  secure:
    BINSTAR_TOKEN: xD5FSNMbD/tMHTSK/fjZ7L3CouztAvDTTib83yhxXDRvL8o76d/otiahbmz4vKfIhvQhCjl4mY+BoAp9EjeRHE1MJGiaWwZZMMvs3w2q7uhuSXsLS1F8IFK4tNWV43j8hwO8zsU3i7TgB+z9uYc3dZ1MwNN39WTYm9mf+GpQc1LNhZHBo+0IYtngu3Ms1zr3sHIY9FszOi9tsL3GNxMazkUjeiSjEqmQPCexR1Ka/mM1xOA1uETx5MWhfeY+yYoyHqdh6p5pQW+CiSj7DjHKfl8j33XTIsNBi4vp9rfWB5HSIIAKUuGpf8uAevOigWlsDsVvIwaofByJ5Y76FtzwGQrN0AN2eVSMyUw7dqI5q4DfXXJaetazki1OjonHr5KFoTSWOHQX7DyaewV7zNvbxYxvmfuxo2pvT9kdY8o0Jt2bqqNxeLKASZL/puFSIy/D2qAGWfz0X7DGD8uHmdU+E6PifaSiWW2qPmZOyxjiaFSBQpkS6xOd06QEz1YvP3FPkoSR+fu604gWnFf56B5lu1qis+n6rOYWrDWCtuSjClhkXYsC6s2zu+igE7G4JEczl6whq4lnxZBp78lhWvl7eFfTke1DeDVc90LN91pU6ofpWUt00Z+gipAEwBxbpJn5cGg8X5PrBgEU9vjZJV9udZQPcKJgafCosXo9zHD99ks=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
